# Exceptions
validation.user.subscribe.self.error=User cannot subscribe to himself